articles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<page>\d+)/$', views.index, name="index"),
    url(r'^(?P<id>\d+)/(?P<article_slug>.+)/$', views.article, name="article"),
]

dafl/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("website.urls", namespace="website")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^articles/', include("articles.urls", namespace="articles")),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^poll/', include('poll.urls', namespace="poll")),
    url(r'^football-center/', include("stats.urls", namespace="stats")),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^registration/', include("registration.urls", namespace="registration")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

YESNO_CHOICES = (
    (True, "Yes"),
    (False, "No"),
)

class Article(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    published = models.BooleanField(choices=YESNO_CHOICES, default=True)
    featured = models.BooleanField(choices=YESNO_CHOICES, default=True)
    title = models.CharField(max_length=150)
    author_name = models.CharField(max_length=150)
    intro_text = models.TextField(blank=True, null=True)
    image = models.FileField(upload_to="articles/intro-images", blank=True, null=True, max_length=200)
    content = RichTextUploadingField(blank=True, null=True)
    tags = models.CharField(max_length=250)

    def __str__(self):
        return self.title


class Video(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    published = models.BooleanField(choices=YESNO_CHOICES, default=True)
    title = models.CharField(max_length=150)
    image = models.FileField(max_length=200, upload_to="articles/videos")
    youtube_link = models.CharField(max_length=300)

    def __str__(self):
        return self.title

articles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.shortcuts import render
from .models import Article

def index(request, page):

    page=int(page)
    print("page=", page)
    print("hereherehereherehereherehereherehereherehereherehereherehereherehere")
    

    latest_articles_list = Article.objects.filter(published=True).order_by("-date_added")
    print("page=", page)

    paginator = Paginator(latest_articles_list, 4)

    try:
        latest_articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        latest_articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        latest_articles = paginator.page(paginator.num_pages)


    return render(request, "articles/index.html", {
    "articles":latest_articles,
    })


def article(request, id, article_slug):
    article = Article.objects.get(pk=id)
    latest_articles = Article.objects.filter(published=True).order_by("-date_added")[:3]

    return render(request, "articles/article.html", {
    "article":article,
    "articles":latest_articles,
    })

templates/articles/article.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{article.title}}
{% endblock title %}

{% block content %}
<div class="blog-container-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="blog-container">
                    <!-- START BLOG ITEMS -->
                    <div class="row">
                      <div class="col-md-12 section-title profile-title">
                          <h1 style="color:black;">{{article.title}}</h1>
                      </div>
                      <hr />
                        <div class="col-md-12">
                            <div class="blog-single-thumb">
                                <img src="{{article.image.url}}" alt="" class="img-responsive">
                            </div>
                            <div class="blog-single-content-title">
                                <span><i class="fa fa-clock-o"></i>{{article.date_added}}</span>
                                <ul class="blog-share">
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fa fa-vk"></i></a></li>
                                    <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                                    <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                                </ul>
                            </div>
                            <div class="blog-single-content">
                                {{article.content|safe}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- END OF /. BLOG CONTAINER SECTION -->
{% endblock content %}

templates/articles/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Latest Articles
{% endblock title %}

{% block content %}

<!-- START PAGE TITILE SECTION -->
<div class="player-profile-section page-title-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="section-title profile-title">
                    <h1>Latest Articles</h1>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="pagination-area">
                    <ul>
                        <li><a href="{% url "website:index" %}">Home<i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
                        <li class="active"><a href="{% url "articles:index" 1%}">Articles</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END OF /. PAGE TITLE SECTION -->

<div class="blog-container-section">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="blog-container">
                    <!-- START BLOG ITEMS -->
                    <div class="row">
                      {% if not articles %}
                        <div class="col-md-12">
                          <h3>Currently there are no articles published, please check back again later for more articles and updates.</h3>
                        </div>
                      {% else %}
                        {% for each in articles %}
                          <div class="col-md-6">
                              <div class="blog-items">
                                  <a href="{% url "articles:article" each.pk each.title|slugify %}">
                                      <span>Article</span>
                                      <img src="{{each.image.url}}" alt="" class="img-responsive" style="height:226px;" />
                                      <div class="blog-content-title">
                                          <h3>{{each.title}}</h3>
                                          <span><i class="fa fa-clock-o"></i>{{each.date_added}}</span>
                                      </div>
                                  </a>
                              </div>
                          </div>
                        {% endfor %}
                        <div class="col-md-12">
                            <nav aria-label="Page navigation" class="navigation">
                                <ul class="pagination">
                                  {% if articles.has_previous %}
                                    <li>
                                      <a href="{% url "articles:index" articles.previous_page_number %}" aria-label="Previous">
                                            <i class="fa fa-chevron-left" aria-hidden="true"></i>
                                            <span aria-hidden="true">Prev</span>
                                        </a>
                                    </li>
                                  {% else %}
                                  <li></li>

                                  {% endif %}

                                    <!-- <li><a href="#">1</a></li> -->
                                    <li class="active">
                                      <a href="#">
                                        <span aria-hidden="true">
                                          Page {{ articles.number }} of {{ articles.paginator.num_pages }}
                                        </span>

                                      </a>
                                    </li>

                                    <!-- <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li> -->
                                     {% if articles.has_next %}
                                    <li>
                                       <a href="{% url "articles:index" articles.next_page_number %}" aria-label="Next">
                                            <span aria-hidden="true">Next</span>
                                            <i class="fa fa-chevron-right" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    {% else %}
                                    <li></li>

                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                      {% endif %}

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="sidebar">
                    <div class="widget">
                        <div class="widget-title">
                            <h3>Today on DAFL</h3>
                        </div>
                        <div class="widget-container">
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner" role="listbox">
                                    <div class="item active">
                                        <ul class="sport-item">
                                            <li>
                                                <a href="#">
                                                    <img src="images/next-game.jpg" class="img-responsive" width="310" height="220" alt="">
                                                    <h3>Best Player in Europe final three: Cristiano Ronaldo</h3>
                                                </a>
                                            </li>
                                        </ul>
                                    </div><!-- end of slider /. item -->
                                    <div class="item">
                                        <ul class="sport-item">
                                            <li>
                                                <a href="#">
                                                    <img src="images/next-game.jpg" class="img-responsive" width="310" height="220" alt="">
                                                    <h3>Best Player in Europe final three: Cristiano Ronaldo</h3>
                                                </a>
                                            </li>
                                        </ul>
                                    </div><!-- end of slider /. item -->
                                    <div class="item">
                                        <ul class="sport-item">
                                            <li>
                                                <a href="#">
                                                    <img src="images/next-game.jpg" class="img-responsive" width="310" height="220" alt="">
                                                    <h3>Best Player in Europe final three: Cristiano Ronaldo</h3>
                                                </a>
                                            </li>
                                        </ul>
                                    </div><!-- end of slider /. item -->
                                    <div class="item">
                                        <ul class="sport-item">
                                            <li>
                                                <a href="#">
                                                    <img src="images/next-game.jpg" class="img-responsive" width="310" height="220" alt="">
                                                    <h3>Best Player in Europe final three: Cristiano Ronaldo</h3>
                                                </a>
                                            </li>
                                        </ul>
                                    </div><!-- end of slider /. item -->
                                    <div class="item">
                                        <ul class="sport-item">
                                            <li>
                                                <a href="#">
                                                    <img src="images/next-game.jpg" class="img-responsive" width="310" height="220" alt="">
                                                    <h3>Best Player in Europe final three: Cristiano Ronaldo</h3>
                                                </a>
                                            </li>
                                        </ul>
                                    </div><!-- end of slider /. item -->

                                </div>
                                <ol class="carousel-indicators sport-item slider-game-time">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active">
                                        <a href="#">
                                            <span>16:48</span>
                                            <p>Best Player in Europe final three: Cristiano Ronaldo</p>
                                        </a>
                                    </li>
                                    <li data-target="#carousel-example-generic" data-slide-to="1">
                                        <a href="#">
                                            <span>15:24</span>
                                            <p>Sweden and Germany in last four</p>
                                        </a>
                                    </li>
                                    <li data-target="#carousel-example-generic" data-slide-to="2">
                                        <a href="#">
                                            <span>12:28</span>
                                            <p>Men's Olympic football: day three</p>
                                        </a>
                                    </li>
                                    <li data-target="#carousel-example-generic" data-slide-to="3">
                                        <a href="#">
                                            <span>11:42</span>
                                            <p>Carvajal wins Super Cup for Madrid</p>
                                        </a>
                                    </li>
                                     <li data-target="#carousel-example-generic" data-slide-to="4">
                                        <a href="#">
                                            <span>11:42</span>
                                            <p>Praise for City signing John Stones</p>
                                        </a>
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                    <div class="widget">,
                        <div class="widget-title">
                            <h3>Latest News</h3>
                        </div>
                        <div class="widget-container">
                            <div class="widget-latest-blog">
                              {% if not articles %}
                                <div class="col-md-12">
                                  <h3 style="color:white;">Currently there are no articles published, please check back again later for more articles and updates.</h3>
                                </div>
                              {% else %}
                                {% for each in articles %}
                                <div class="blog-items-sm latest-blog">
                                    <a href="{% url "articles:article" each.pk each.title|slugify %}">
                                        <div class="thumbnail">
                                            <img src="{{each.image.url}}" class="img-responsive" width="120" height="120" alt="">
                                        </div>
                                        <div class="blog-content">
                                            <span>Article</span>
                                            <h3>{{each.title}}</h3>
                                            <p><i class="fa fa-clock-o"></i>{{each.date_added}}</p>
                                        </div>
                                    </a>
                                </div>
                                {% endfor %}
                              {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- END OF /. BLOG CONTAINER SECTION -->

{% endblock content %}