dafl/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("website.urls", namespace="website")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^articles/', include("articles.urls", namespace="articles")),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^poll/', include('poll.urls', namespace="poll")),
    url(r'^football-center/', include("stats.urls", namespace="stats")),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^registration/', include("registration.urls", namespace="registration")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stats/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/roster/$', views.teamRoster, name="team-roster"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/schedule/$', views.teamSchedule, name="team-schedule"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/$', views.teamPage, name="team-page"),
    url(r'^teams/$', views.teamIndex, name="team-index"),
    url(r'^league/(?P<league_id>\d+)/(?P<league_slug>.+)/$', views.leaguePage, name="league-page"),
    url(r'^cups-and-leagues/(?P<cup_id>\d+)/(?P<cup_name>.+)/$', views.cupPage, name="cup-page"),
    url(r'^cups-and-leagues/$', views.clIndex, name="cups-and-leagues"),
    url(r'^players/$', views.playerIndex, name="players"),
    url(r'^players/(?P<player_id>\d+)/(?P<player_slug>.+)/$', views.playerPage, name="player-page"),
    url(r'^match/(?P<match_id>\d+)/(?P<match_slug>.+)/$', views.matchPage, name="match"),
]

website/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^feedback/$', views.feedback, name="feedback"),
]

templates/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js" lang="en">

<head>
        <!-- meta -->
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- web site title -->
        <title>{% block title %}{% endblock title %} - Delhi Amateur Football League</title>

        <!-- favicon -->
        <link rel="icon" href="{% static "images/favicon.png" %}">

        <!-- style -->
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <link rel="stylesheet" href="{% static "css/custom.css" %}">

        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js" %}"></script>
            <script>window.html5 || document.write('<script src="js/vendor/html5shiv.js" %}"><\/script>')</script>
        <![endif]-->
    </head>
    <body>
      <div class="wrapper">

        {% include "header.html" %}

        {% block content %}
        {% endblock content %}

        {% include "footer.html" %}

      </div>

    <script src="{% static "js/vendor/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery-ui-min.js" %}"></script>
    <script src="{% static "js/owl.carousel.min.js" %}"></script>
    <script src="{% static "js/jquery.downCount.js" %}"></script>
    <script src="{% static "js/bootsnav.js" %}"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script src="{% static "js/isotope.pkgd.min.js" %}"></script>
    <script src="{% static "js/jquery.prettyPhoto.js" %}"></script>
    <script src="{% static "scripts/Tweetie/tweetie.min.js" %}"></script>
    <script src="{% static "js/jquery.appear.js" %}"></script>
    <script src="{% static "js/waypoints.min.js" %}"></script>
    <script src="{% static "js/jQuery-plugin-progressbar.js" %}"></script>
    <script src="{% static "js/v.carousel.js" %}"></script>
    <script src="{% static "js/custom.js" %}"></script>
</body>
</html>

templates/blog-single-2.html
<html><head><title>Error 404 - Not Found</title><head><body><h1>Error 404 - Not Found</h1><p>The document you are looking for may have been removed or re-named. Please contact the web site owner for further assistance.</p></body></html>

templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Contact Us
{% endblock title %}

{% block content %}

{% if status == "done" %}
  <script type="text/javascript">
    alert("Your query has been submitted! We'll get in touch with you soon!");
  </script>
{% endif %}

{% if status == "fail" %}
  <script type="text/javascript">
    alert("Your query could not be recorded, please try again after few minutes.");
  </script>
{% endif %}

  <!-- START PAGE TITILE SECTION -->
  <div class="page-title-section contact-page-title">
      <div class="container">
          <div class="row">
              <div class="col-md-12">
                  <div class="page-title">
                      <h2>Contact Us</h2>
                      <p>Need Help or Promotion?</p>
                  </div>
              </div>
          </div>
      </div>
  </div> <!-- END OF /. PAGE TITLE SECTION -->

  <!-- START CONTACT INFO SECTION -->
  <div class="contact-info-section">
      <div class="container">
          <div class="row">
              <div class="col-md-4">
                  <div class="info-items">
                      <i class="fa fa-envelope"></i>
                      <h4>Our Email</h4>
                      <p>aasheesh@footballandmee.com</p>
                  </div>
              </div><!-- END OF /. COL -->
              <div class="col-md-4">
                  <div class="info-items">
                      <i class="fa fa-phone"></i>
                      <h4>Our Phones</h4>
                      <p>+91-8800558899 </p>
                  </div>
              </div><!-- END OF /. COL -->
              <div class="col-md-4">
                  <div class="info-items">
                      <i class="fa fa-map-marker" aria-hidden="true"></i>
                      <h4>Our Address  <i class="fa fa-arrow-circle-down" aria-hidden="true"></i></h4>
                      <p>The BallPark, Carterpuri Marg</p>
                      <p>Palam Vihar Extension, Gurugram, Haryana</p>
                  </div>
              </div><!-- END OF /. COL -->
          </div>
          <div class="row">
              <div class="col-md-8 col-md-offset-2">
                  <div class="contact-title">
                      <h3>Fill in the contact form and we'll get in touch with you</Span></h3>
                  </div>
              </div>
              <div class="col-md-8 col-md-offset-2">
                  <form action="{% url "website:contact" %}" class="row comment-reply contact-form" method="post">
                    {% csrf_token %}
                      <div class="col-md-6 form-group">
                          <input type="text" class="form-control" name="name" placeholder="Name*">
                      </div>
                      <div class="col-md-6 form-group">
                          <input type="email" class="form-control" name="email" placeholder="Email*">
                      </div>
                      <div class="col-md-12 form-group">
                          <input type="text" class="form-control" name="phone" placeholder="Mobile*">
                      </div>
                      <div class="col-md-12 form-group">
                          <textarea class="form-control" name="message" cols="30" rows="6" placeholder="Your message"></textarea>
                      </div>
                      <div class="col-md-12">
                          <input type="submit" class="comment-submit" value="Submit Your Message">
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div><!-- END OF /. CONTACT INFO SECTION  -->

  <div class="map-section">
      <div class="container-fluid">
          <div class="row">
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel panel-default">
                  <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <span>Hide Map</span>
                      </a>
                    </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div id="map"></div>
                  </div>
                </div>
              </div>
          </div>
      </div>
  </div>

{% endblock content %}

templates/feedback.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Contact Us
{% endblock title %}

{% block content %}

{% if status == "done" %}
  <script type="text/javascript">
    alert("Your query has been submitted! We'll get in touch with you soon!");
  </script>
{% endif %}

{% if status == "fail" %}
  <script type="text/javascript">
    alert("Your query could not be recorded, please try again after few minutes.");
  </script>
{% endif %}

  <!-- START PAGE TITILE SECTION -->
  <div class="page-title-section contact-page-title">
      <div class="container">
          <div class="row">
              <div class="col-md-12">
                  <div class="page-title">
                      <h2>Feedback</h2>                      
                  </div>
              </div>
          </div>
      </div>
  </div> <!-- END OF /. PAGE TITLE SECTION -->

  <!-- START CONTACT INFO SECTION -->
  <div class="contact-info-section">
      <div class="container">
          <div class="row">
              <div class="col-md-4">
                  <div class="info-items">
                      <i class="fa fa-envelope"></i>
                      <h4>Our Email</h4>
                      <p>aasheesh@footballandmee.com</p>
                  </div>
              </div><!-- END OF /. COL -->
              <div class="col-md-4">
                  <div class="info-items">
                      <i class="fa fa-phone"></i>
                      <h4>Our Phones</h4>
                      <p>+91-8800558899 </p>
                  </div>
              </div><!-- END OF /. COL -->
              <div class="col-md-4">
                  <div class="info-items">
                      <i class="fa fa-map-marker" aria-hidden="true"></i>
                      <h4>Our Address  <i class="fa fa-arrow-circle-down" aria-hidden="true"></i></h4>
                      <p>The BallPark, Carterpuri Marg</p>
                      <p>Palam Vihar Extension, Gurugram, Haryana</p>
                  </div>
              </div><!-- END OF /. COL -->
          </div>
          <div class="row">
              <div class="col-md-8 col-md-offset-2">
                  <div class="contact-title">
                      <h3>Fill in the contact form and we'll get in touch with you</Span></h3>
                  </div>
              </div>
              <div class="col-md-8 col-md-offset-2">
                  <form action="{% url "website:contact" %}" class="row comment-reply contact-form" method="post">
                    {% csrf_token %}
                      <div class="col-md-6 form-group">
                          <input type="text" class="form-control" name="name" placeholder="Name*">
                      </div>
                      <div class="col-md-6 form-group">
                          <input type="email" class="form-control" name="email" placeholder="Email*">
                      </div>
                      <div class="col-md-12 form-group">
                          <input type="text" class="form-control" name="phone" placeholder="Mobile*">
                      </div>
                      <div class="col-md-12 form-group">
                          <textarea class="form-control" name="message" cols="30" rows="6" placeholder="Your message"></textarea>
                      </div>
                      <div class="col-md-12">
                          <input type="submit" class="comment-submit" value="Submit Your Message">
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div><!-- END OF /. CONTACT INFO SECTION  -->

  <div class="map-section">
      <div class="container-fluid">
          <div class="row">
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel panel-default">
                  <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <span>Hide Map</span>
                      </a>
                    </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div id="map"></div>
                  </div>
                </div>
              </div>
          </div>
      </div>
  </div>

{% endblock content %}

templates/footer.html
{% load staticfiles %}
<!-- start twitter section -->
<div class="twitter-tweit-section">
    <div class="container-fluid footer-top-bg left-arrow-bg">
        <div class="row">
            <div class="col-md-3 bg-parent gry-bg">
                <Div class="right-bg-g"></Div>
            </div>
        </div>
    </div><!-- arrow shape -->
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="titter-title">
                    <h3><i class="fa fa-twitter"></i>  Recent Tweets</h3>
                    <span>Find Us:  @THE_DAFL</span>
                </div>
            </div><!-- twiiter title -->
            <div class="col-md-7">
                <div class="twitter-slide">
                    <div class="owl-carousel" id="twitter-slide">
                        <div class="item">
                            <p>The 2016 UEFA European Championship, commonly referred to as UEFA Euro 2016 or simply Euro 2016, was the 15th UEFA European</p>
                        </div>
                        <div class="item">
                            <p>The 2016 UEFA European Championship, commonly referred to as UEFA Euro 2016 or simply Euro 2016, was the 15th UEFA European</p>
                        </div>
                        <div class="item">
                            <p>The 2016 UEFA European Championship, commonly referred to as UEFA Euro 2016 or simply Euro 2016, was the 15th UEFA European</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1">
                <div class="twitter-navigation">
                    <button class="twitter-next"><i class="fa fa-chevron-right" aria-hidden="true"></i></button>
                    <button class="twitter-perv"><i class="fa fa-chevron-left" aria-hidden="true"></i></button>
                </div>
            </div><!-- end of /. col -->
        </div><!-- end of /. row -->
    </div><!-- end of /. container -->
</div><!-- end of /. twitter section -->

<!-- satrt footer top section -->
<div class="section footer-top-section">
    <div class="container-fluid footer-top-bg">
        <div class="row">
            <div class="col-md-5 col-md-offset-7 bg-parent">
                <Div class="right-bg-g"></Div>
            </div>
        </div><!-- bg arrow shape -->
    </div><!-- end of /. container -->
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="footer-widget">
                    <div class="widget-title">
                        <h3>About DAFL</h3>
                    </div>
                    <div class="widget-container">
                        <ul>
                           <li><a href="/pages/the-management/">The Management</a></li>
                            <li><a href="/pages/the-league/">The League</a></li>
                            <li><a href="/pages/format/">Format</a></li>
                            <li><a href="/pages/dafl-advantage/">DAFL Advantages</a></li>
                        </ul>
                    </div>
                </div><!-- end of /. widget  -->
            </div><!-- end of /. col-md-2 -->
            <div class="col-md-2">
                <div class="footer-widget">
                    <div class="widget-title">
                        <h3>Regulations</h3>
                    </div>
                    <div class="widget-container">
                        <ul>
                           <li><a href="/pages/player-eligibility/">Player's Eligibility</a></li>
                            <li><a href="/pages/code-of-conduct/">Code of Conduct</a></li>
                            <li><a href="/pages/rules-u711/">Rules for U-7 to U-11</a></li>
                            <li><a href="/pages/rules-other/">Rules for Rest</a></li>
                        </ul>
                    </div>
                </div><!-- end of /. widget  -->
            </div><!-- end of /. col-md-2 -->
            <div class="col-md-2">
                <div class="footer-widget">
                    <div class="widget-title">
                        <h3>Support</h3>
                    </div>
                    <div class="widget-container">
                        <ul>
                           <li><a href="{% url "website:contact" %}">Contact Us</a></li>
                            <li><a href="{% url "website:feedback" %}">Feedback</a></li>
                            <li><a href="/pages/faq/">FAQ</a></li>
                            <li><a href="/pages/location/">Location</a></li>
                        </ul>
                    </div>
                </div><!-- end of /. widget  -->
            </div><!-- end of /. col-md-2 -->
            <div class="col-md-2">
                <div class="footer-widget">
                    <div class="widget-title">
                        <h3>Policies</h3>
                    </div>
                    <div class="widget-container">
                        <ul>
                           <li><a href="/pages/privacy-policy/">Privacy Policy</a></li>
                            <li><a href="/pages/cookie-policy/">Cookie Policy</a></li>
                            <li><a href="/pages/terms-and-conditions/">Terms &amp; Conditions</a></li>
                            <li><a href="/pages/returns-and-refunds/">Returns &amp; Refunds</a></li>
                        </ul>
                    </div>
                </div><!-- end of /. widget  -->
            </div><!-- end of /. col-md-2 -->
            <div class="col-md-4">
                <div class="footer-logo">
                    <a href="#">
                        <img src="{% static "images/logo.png" %}" class="img-responsive" width="175" alt="">
                    </a>
                </div><!-- end of /. footer logo -->
            </div><!-- end of /.col -->
        </div><!-- end of /. row -->
    </div><!-- end of /. container -->
</div><!-- end of /. footer top -->

<!-- star footer  -->
<div class="footer-section">
    <div class="container-fluid footer-top-bg">
        <div class="row">
            <div class="col-md-5 col-md-offset-7 bg-parent">
                <Div class="right-bg-g"></Div>
            </div>
        </div><!-- end of /. row -->
    </div><!-- end of /. container -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6">
                <div class="alignleft copyright">
                    <p>&copy; All rights reserved by Football and Mee | Powered by <a href="http://www.indigeniussports.com/" target="_blank">IndiGenius Sports</a></p>
                </div><!-- end of /. copyright -->
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="footer-social">
                    <p>Follow Us:</p>
                    <ul>
                        <li><a href="http://www.facebook.com/TheDAFL" target="_blank"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="http://www.twitter.com/The_DAFL" target="_blank"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-vk"></i></a></li>
                        <li><a href="http://www.instagram.com/The_DAFL" target="_blank"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                        <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
                    </ul>
                </div><!-- end of /. follow  -->
            </div> <!-- end of /. col -->
        </div><!-- end of /. row -->
    </div><!-- end of /. container -->
</div><!-- end of /. footer -->

templates/header.html
{% load staticfiles %}
  <style>


  </style>

<div class="header-section">
    <!-- Start Navigation -->
    <nav class="navbar navbar-default cart">
        <div class="container">
            <!-- Start Header Navigation -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed top-m-btn" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "website:index" %}"><img src="{% static "images/logo.png" %}" alt=""></a>
                <a href="{% url "registration:index" %}"><img src="{% static "images/top-banner.png" %}" class="header-banner img-responsive" /></a>
            </div>
            <!-- End Header Navigation -->

            <!-- Collect the nav links, forms, and other content for toggling -->

        </div><!-- end of /. container -->
    </nav><!-- End Navigation -->

    <!-- START MENU SECTION -->
    <nav class="navbar navbar-default bootsnav">
        <div class="container">
            <!-- Start Atribute Navigation -->
            <!-- <div class="attr-nav">
                <ul>
                    <li class="search">
                        <form action="#">
                            <input type="text" name="search" placeholder="Search"  />
                            <button><i class="fa fa-search"></i></button>
                        </form>
                    </li>
                </ul>
            </div> -->
            <!-- End Atribute Navigation -->

             <!-- Start Header Navigation -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <!-- End Header Navigation -->

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-menu">
                <ul class="nav navbar-nav navbar-left" data-in="zoomIn" data-out="zoomOut">
                    <li class="dropdown"><a href="#" class="dropdown-toggle">The DAFL</a>
                      <ul class="dropdown-menu">
                          <li><a href="/pages/the-management/">The Management</a></li>
                          <li><a href="/pages/the-league/">The League</a></li>
                          <li><a href="/pages/format/">Format</a></li>
                          <li><a href="/pages/player-eligibility/">Player's Eligibility</a></li>
                          <li><a href="/pages/dafl-advantage/">DAFL Advantages</a></li>
                          <li><a href="/pages/code-of-conduct">Code of Conduct</a></li>
                          <li><a href="/pages/location">Location</a></li>
                          <li><a href="/pages/faq">FAQ</a></li>
                      </ul>
                    </li>
                     <!-- <a href="?page={{ contacts.previous_page_number }}"> -->
                    <li><a href="{% url "articles:index" 1 %}">Articles</a></li>
                    <li><a href="{% url "stats:team-index" %}">Teams</a>
                    </li>

                    <li class="dropdown"><a href="#" class="dropdown-toggle">League Center</a>
                      <ul class="dropdown-menu">
                        {% for each in competitions %}
                          <li><a href="{% url "stats:league-page" each.pk each.name|slugify %}">{{each.name}}</a></li>
                        {% endfor %}
                      </ul>
                    </li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle">Associations</a>
                    </li>
                    <li class="dropdown"><a href="#" class="dropdown-toggle">Fan Zone</a>
                      <ul class="dropdown-menu">
                          <li><a href="#">Photos</a></li>
                          <li><a href="#">Videos</a></li>
                          <li><a href="#">Social Wall</a></li>
                          <li><a href="#">Media Watch</a></li>
                          <li><a href="#">Merchandise</a></li>
                      </ul>
                    </li>
                    <li><a href="{% url "website:contact" %}">Contact Us</a></li>
                    <li style="background-color:red;"><a href="{% url "registration:index" %}">Register</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- end of container -->
    </nav><!-- end of /. nav -->


    <div data-spy="affix" >
      <div class="container-fluid" >
          <a href="{% url "registration:index" %}" >
            {# <font size="3">&nbsp &nbsp Register &nbsp  &nbsp </font> #}
            <img src="{%static '/images/sticky_menu/reg.png'%}" style="width:120px;height:40px;"  alt="">
          </a>
          <a href="" >
            {# <font size="3">&nbsp  &nbsp Pay Now &nbsp  &nbsp  &nbsp</font> #}
            <img src="{%static '/images/sticky_menu/pay.png'%}" style="width:130px;height:40px;"  alt="">

          </a>
     </div>
   </div>

</div><!-- end of /. nav area-->
<!-- End Navigation -->