dafl/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("website.urls", namespace="website")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^articles/', include("articles.urls", namespace="articles")),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^poll/', include('poll.urls', namespace="poll")),
    url(r'^football-center/', include("stats.urls", namespace="stats")),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^registration/', include("registration.urls", namespace="registration")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stats/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/roster/$', views.teamRoster, name="team-roster"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/schedule/$', views.teamSchedule, name="team-schedule"),
    url(r'^teams/(?P<team_id>\d+)/(?P<team_slug>.+)/$', views.teamPage, name="team-page"),
    url(r'^teams/$', views.teamIndex, name="team-index"),
    url(r'^league/(?P<league_id>\d+)/(?P<league_slug>.+)/$', views.leaguePage, name="league-page"),
    url(r'^cups-and-leagues/(?P<cup_id>\d+)/(?P<cup_name>.+)/$', views.cupPage, name="cup-page"),
    url(r'^cups-and-leagues/$', views.clIndex, name="cups-and-leagues"),
    url(r'^players/$', views.playerIndex, name="players"),
    url(r'^players/(?P<player_id>\d+)/(?P<player_slug>.+)/$', views.playerPage, name="player-page"),
    url(r'^match/(?P<match_id>\d+)/(?P<match_slug>.+)/$', views.matchPage, name="match"),
]

stats/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from ckeditor_uploader.fields import RichTextUploadingField

FORMAT_CHOICES = (
    (1, "League"),
    (2, "League + Knockout"),
    (3, "Group-Wise League + Knockout"),
    (4, "Group-Wise League + Leauge"),
    (5, "Group Wise League + Group Wise League + Knockouts"),
    (6, "League + Group-wise Leauge"),
    (7, "Group-wise League + League + Knockout"),
)
PLAYER_TYPES = (
    (1, "Centre-back"),
    (2, "Sweeper"),
    (3, "Full-back"),
    (4, "Wing-back"),
    (5, "Centre midfield"),
    (6, "Defensive midfield"),
    (7, "Attacking midfield"),
    (8, "Wide midfield"),
    (9, "Centre forward"),
    (10, "Second striker"),
    (11, "Winger"),
    (12, "Goalkeeper"),
    (13, "Defensive"),
    (14, "Midfield"),
    (15, "Attacking"),
)

MANAGER_TYPES = (
    (1, "Technical Director"),
    (2, "Head Coach"),
    (3, "Asst. Coach"),
    (4, "GK Coach"),
    (5, "Manager"),
)

class Competition(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    league_format = models.IntegerField(choices=FORMAT_CHOICES, default=0)
    logo = models.FileField(upload_to="competitions/logos/", max_length=150)

    def __str__(self):
        return self.name

class Season(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=50)
    competiton = models.ForeignKey(Competition)

    def __str__(self):
        return self.name

class Venue(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    address = models.TextField(blank=True, null=True)
    city = models.CharField(blank=True, null=True, max_length=50)
    def __str__(self):
        return self.name

class Player(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    picture = models.FileField(max_length=150, upload_to="players", blank=True, null=True)
    dob = models.DateField(blank=True, null=True, help_text="Date of Birth")
    nationality = models.CharField(max_length=50, default="Indian")
    height = models.IntegerField(default=100)
    weight = models.FloatField(default=100)
    player_type = models.IntegerField(choices=PLAYER_TYPES, default=0)
    about= models.CharField(max_length=500, null=True)
    def __str__(self):
        return self.name

class Management(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    picture = models.FileField(max_length=150, upload_to="management", blank=True, null=True)
    dob = models.DateField(blank=True, null=True, help_text="Date of Birth")
    nationality = models.CharField(max_length=50, default="Indian")
    height = models.IntegerField(default=100)
    weight = models.FloatField(default=100)
    manager_type = models.IntegerField(choices=MANAGER_TYPES, default=0)

    def __str__(self):
        return self.name

class Team(models.Model):
    date_added = models.DateField(default=timezone.now)
    competition = models.ForeignKey(Competition, blank=True, null=True, related_name='competition_admin')
    name = models.CharField(max_length=50)
    logo = models.FileField(upload_to="teams/logos", blank=True, null=True, max_length=150)
    state = models.CharField(max_length=35)
    players=models.ManyToManyField(Player)
    managers=models.ManyToManyField(Management)
    locations=models.CharField(max_length=35, null=True)
    about= models.CharField(max_length=500, null=True)
    email=models.EmailField(null=True)
    contact_no = PhoneNumberField(null=True)

    def __str__(self):
        return self.name


class Match(models.Model):
    date_added = models.DateField(default=timezone.now)
    date_of_match = models.DateField()
    season = models.ForeignKey(Season, default=None)
    preview = RichTextUploadingField(blank=True, null=True)
    report = RichTextUploadingField(blank=True, null=True)
    home_team = models.ForeignKey(Team, related_name="home")
    home_players_playing = models.ManyToManyField(Player, blank=True, related_name="home_players")
    home_players_substitutes = models.ManyToManyField(Player, blank=True, related_name="home_players_subs")
    away_team = models.ForeignKey(Team, related_name="away")
    away_players_playing = models.ManyToManyField(Player, blank=True, related_name="away_players")
    away_players_substitutes = models.ManyToManyField(Player, blank=True, related_name="away_players_subs")
    home_score = models.IntegerField(default=0)
    away_score = models.IntegerField(default=0)
    match_location = models.ForeignKey(Venue)
    published = models.BooleanField(default=False, choices=(
        (True, "Yes"),
        (False, "No"),
    ))

    def __str__(self):
        #return "Match between " + self.home_team.name + " and " + self.away_team.name + " on " + str(self.date_of_match) + " at " + self.match_location
        return "Match between " + self.home_team.name + " and " + self.away_team.name
    def match_description(self):
        #return "Match between " + self.home_team.name + " and " + self.away_team.name + " on " + str(self.date_of_match) + " at " + self.match_location
        return "Match between " + self.home_team.name + " and " + self.away_team.name

    def getHome(self):
        return self.home_team.name

    def getAway(self):
        return self.away_team.name

class TopPlayer(models.Model):
    date_added = models.DateField(default=timezone.now)
    player = models.ForeignKey(Player)

    def __str__(self):
        return self.player.name

class PointTable(models.Model):
    date_added = models.DateField(default=timezone.now)
    competition = models.ForeignKey(Competition)

    def __str__(self):
        return self.competition.name

class TeamPoint(models.Model):
    competition = models.ForeignKey(PointTable)
    team = models.ForeignKey(Team)
    points = models.IntegerField(default=0)
    wins = models.IntegerField(default=0)
    lose = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    goal_for=models.IntegerField(default=0)
    goal_against=models.IntegerField(default=0)
    goal_diff=models.IntegerField(default=0)

stats/views.py
from django.shortcuts import render
from datetime import datetime, timedelta
from .models import Team, Match, Competition, Player, Season, PointTable, TeamPoint

teams = Team.objects.all().order_by("-date_added")


def index(request):
    return render(request, "index.html", {

    })

def clIndex(request):
    return render(request, "index.html", {

    })

def cupPage(request, cup_id, cup_name):
    return render(request, "index.html", {

    })


def playerPage(request, player_id, player_slug):
    player_id = int(player_id)
    player = Player.objects.get(pk=player_id)
    print ("player=", player);
    return render(request, "stats/player.html", {
        "player":player,
    })

def playerIndex(request):
    return render(request, "players.html", {

    })

def matchPage(request, match_id, match_slug):
    match=Match.objects.get(pk=match_id);
    for each in match.home_players_playing.all():
        print each.picture.url
    return render(request, "stats/match.html", {
        'match': match,
    })

def teamIndex(request):
    competitions = Competition.objects.all()
    teams = Team.objects.all()
    for each in competitions:
        each.team_set.all()

    return render(request, "stats/teams.html", {
    })

def teamPage(request, team_id, team_slug):
    team_id = int(team_id)
    team = Team.objects.get(pk=team_id)
    matches=Match.objects.filter(home_team=team_id)


    # for each in matches:
    #     print("teams in all matches=", each.home_team, each.away_team)
    #     if team_id==each.home_team or team_id==each.away_team:
    #         print("match=", each.name)

    startdate = datetime.today()
    # prevdate = startdate + timedelta(days=-365*100)
    # enddate = startdate + timedelta(days=10)
    # print("startdate", startdate," prevdate", prevdate,  " enddate", enddate)


    #objects.filter(date__range=["2011-01-01", "2011-01-31"])

    # fixtures1=[]
    # fixtures2=[]

    # results1=[]
    # results2=[]

    try:
        fixtures1=(Match.objects.filter(home_team=team_id).filter(date_of_match__gte=startdate))
    except:
        fixtures1 = None
    try:
        fixtures2 = (Match.objects.filter(away_team=team_id).filter(date_of_match__gte=startdate))
    except:
        fixtures2 = None

    try:
        results1.append(Match.objects.filter(home_team=team_id).filter(date_of_match__lt=startdate))
    except:
        results1 = None

    try:
        results2=(Match.objects.filter(away_team=team_id).filter(date_of_match__lt=startdate))

    except:
        results2 = None

    # print("fixtures1=", fixtures1, " results1=",  results1)
    # print("fixtures2=", fixtures2, " results2=",  results2)
    # results1.extend(results2)
    # fixtures1.extend(fixtures2)

    # print("fixtures1=", fixtures1, " results1=",  results1)
    # print("fixtures2=", fixtures2, " results2=",  results2)

    # for each in fixtures1:
    #     print "matchsfkjdbskfjsd=", each.date_added
        #each.home_team, each.away_team, each.date_of_match, each.season.competiton, each.match_location
    # for each in fixtures2:
    #     print each.home_team, each.away_team, each.date_of_match, each.season.competiton, each.match_location

    # for each in results1:
    #     print each.home_team, each.away_team, each.date_of_match, each.season.competiton, each.match_location

    # for each in results2:
    #     print each.home_team, each.away_team, each.date_of_match, each.season.competiton, each.match_location





    return render(request, "stats/team.html", {
        "team":team,
        "fixtures1":fixtures1,
        "results1":results1,
        "fixtures2":fixtures2,
        "results2":results2,

    })

def teamRoster(request, team_id, team_slug):
    team_id = int(team_id)
    team = Team.objects.get(pk=team_id)

    return render(request, "stats/team-roster.html", {
     "team":team,
    })

def teamSchedule(request, team_id, team_slug):
    team_id = int(team_id)
    team = Team.objects.get(pk=team_id)

    print "HERE", team, team_id
    matches=Match.objects.all()
    for each in matches:
        print each.home_team, each.away_team

    try:
        home_matches = Match.objects.filter(home_team=team_id)
    except:
        home_matches=None
    try:
        away_matches = Match.objects.filter(away_team=team_id)
    except:
        away_matches=None


    #home_matches = Match.objects.get(home_team=2)
    print "HERE, home matches=", home_matches

    #away_matches = Match.objects.get(away_team=2)
    print "HERE,  away_matches=", away_matches


    for each in home_matches:
        print each.home_team, each.away_team, each.date_of_match, each.season.competiton, each.match_location

    return render(request, "stats/team-schedule.html", {
     "team":team,
    "away_matches":away_matches, "home_matches":home_matches,
    })


def leaguePage(request, league_id, league_slug):

    league_id = int(league_id)
    league = Competition.objects.get(pk=league_id)
    seasons = Season.objects.filter(competiton=league)
    print "season", seasons

    startdate = datetime.today()

    results=Match.objects.filter(season__in=seasons).filter(date_of_match__lt=startdate)
    fixtures=Match.objects.filter(season__in=seasons).filter(date_of_match__gte=startdate).order_by("-date_of_match")
    print "results", results, "fixtures", fixtures

    teams = Team.objects.filter(competition=league_id);

    pointTable = PointTable.objects.filter(competition=league_id)
    teamPoint = TeamPoint.objects.filter(competition__in=pointTable)

    return render(request, "stats/league.html", {
        "league":league,
        "results":results,
        "fixtures":fixtures,
        "teams": teams,
        "teamPoint": teamPoint

    })

templates/stats/league.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
{{league.name}}
{% endblock title %}

{% block content %}
{% if fixtures|length > 0 %}
<div class="match-today-section">
  <div class="container">

    <div class="row">
      <div class="match-today-features">
        <div class="col-md-4 col-md-12 col-xs-12">
          <div class="match-left">
            <div class="today-team-img teamsname">
              <a href="#"><img src="{{fixtures.0.home_team.logo.url}}" width="65" height="63" alt=""></a>
            </div>
            <div class="today-team-name teamsname">
              <h1>{{fixtures.0.home_team}}</h1>

            </div>
          </div>
        </div>
        <div class="col-md-4 col-md-12 col-xs-12">
          <div class="team-vs-team">
            <h1>VS</h1>
          </div>
        </div>
        <div class="col-md-4 col-md-12 col-xs-12">
          <div class="match-right">
            <div class="today-team-name teamsname">
              <h1>{{fixtures.0.away_team}}</h1>
            </div>
            <div class="today-team-img teamsname">
              <a href="#"><img src="{{fixtures.0.away_team.logo.url}}" width="65" height="63" alt=""></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="nex-match">
          <h2>Next Match: <span>({{fixtures.0.date_of_match}})</span></h2>
          <p><i class="fa fa-map-marker" aria-hidden="true"></i>Location: {{fixtures.0.match_location}}</p>

        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if fixtures|length < 1 %}
<div class="match-today-section">
  <div class="container">

    <div class="row">
      <div class="match-today-features">
        <div class="col-md-12 col-md-12 col-xs-12">
          <div >
            <h1 style="text-align: center;color: white"><b>No Upcoming Match.</b></h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

<div class="club-play-histry">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="super-cup-title">
          <h1><span><b>{{league.name}}</b></span></h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="tab-area">
          <!-- Nav tabs -->

          <ul class="nav nav-tabs nav-justified " role="tablist">
            <li  role="presentation" class="active"><a href="#fixtures" aria-controls="fixtures" role="tab" data-toggle="tab">Fixtures</a></li>
            <li  role="presentation"><a href="#results" aria-controls="results" role="tab" data-toggle="tab">Results</a></li>
            <li  role="presentation"><a href="#points" aria-controls="teams" role="tab" data-toggle="tab">Points Table</a></li>
            <li  role="presentation"><a href="#teams" aria-controls="teams" role="tab" data-toggle="tab">Top Scorers</a></li>
            <li  role="presentation"><a href="#teams" aria-controls="teams" role="tab" data-toggle="tab">Top Assists</a></li>
            <li  role="presentation"><a href="#teams" aria-controls="teams" role="tab" data-toggle="tab">Bookings</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">

            <div role="tabpanel" class="tab-pane active" id="results">
              <div class="fixture-section">
                <div class="container">

                  <div class="row inner-custom-row">
                    <div class="col-md-12">
                      {% for each in results %}

                      <div class="row">
                        <div class="white-match">
                          <div class="col-md-4">
                            <div class="match-left">
                              <div class="fixture-team-img">
                                <a href="{% url "stats:team-page" each.home_team.pk each.home_team.name|slugify %}"><img src="{{each.home_team.logo.url}}" width="80" height="77" alt="image"></a>
                              </div>
                              <div class="fixture-team-name fixture-team-left">
                                <h1>{{each.home_team.name}}</h1>
                                <p>{{each.home_team.state}}</p>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="fixture-team-date">
                              <a href="{% url "stats:match" each.pk each.home_team.name|slugify %}"><h1>{{each.date_of_match}}</h1></a>
                              <a href="{% url "stats:match" each.pk each.home_team.name|slugify %}"><p>{{each.match_location}}</p></a>
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="match-right">
                              <div class="fixture-team-name fixture-team-right text-right">
                                <h1>{{each.away_team.name}}</h1>
                                <p>{{each.away_team.state}}</p>
                              </div>
                              <div class="fixture-team-img">
                                <a href="{% url "stats:team-page" each.away_team.pk each.away_team.name|slugify %}"><img src="{{each.away_team.logo.url}}" width="80" height="77" alt="image"></a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% endfor %}


                    </div>
                  </div>
                </div>
              </div>


            </div>

            <div role="tabpanel" class="tab-pane" id="fixtures">


              <div class="fixture-section">
                <div class="container">

                  <div class="row inner-custom-row">
                    <div class="col-md-12">
                      {% for each in fixtures %}

                      <div class="row">
                        <div class="white-match">
                          <div class="col-md-4">
                            <div class="match-left">
                              <div class="fixture-team-img">
                                <a href="{% url "stats:team-page" each.home_team.pk each.home_team.name|slugify %}"><img src="{{each.home_team.logo.url}}" width="80" height="77" alt="image"></a>
                              </div>
                              <div class="fixture-team-name fixture-team-left">
                                <h1>{{each.home_team.name}}</h1>
                                <p>{{each.home_team.state}}</p>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="fixture-team-date">
                              <h1>{{each.date_of_match}}</h1>
                              <p>{{each.match_location}}</p>
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="match-right">
                              <div class="fixture-team-name fixture-team-right text-right">
                                <h1>{{each.away_team.name}}</h1>
                                <p>{{each.away_team.state}}</p>
                              </div>
                              <div class="fixture-team-img">
                                <a href="{% url "stats:team-page" each.away_team.pk each.away_team.name|slugify %}"><img src="{{each.away_team.logo.url}}" width="80" height="77" alt="image"></a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      {% endfor %}

                    </div>
                  </div>
                </div>
              </div>

            </div>

            <div role="tabpanel" class="tab-pane" id="points">

              <div class="point-table-page">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="point-table-area">
                        <div class="point-title-area">
                          <table class="table">
                            <thead>
                              <tr>
                                <th width="20%" scope="row">Team</th>
                                <!-- <th width="10%" class="text-center">Playered</th> -->
                                <th width="10%" class="text-center">Won</th>
                                <th width="10%" class="text-center">Draw</th>
                                <th width="10%" class="text-center">Lost </th>
                                <th width="10%" class="text-center">For</th>
                                <th width="10%" class="text-center">Against</th>
                                <th width="10%" class="text-center">Goal dif.</th>
                                <th width="10%" class="text-center">Points</th>
                              </tr>
                            </thead>
                          </table>
                        </div>
                        <div class="point-itmes">
                          <table class="table table-striped-inverse point-table">
                            <tbody>
                              {% for each in teamPoint %}
                              <tr>
                                <th data-th="Team" width="20%" scope="row">
                                  <a href= "{% url "stats:team-page" each.team.pk each.team.name|slugify %}">
                                    <img src="{{each.team.logo.url}}" alt="team image" />

                                    <span>{{each.team.name}}</span>
                                  </a>
                                </th>
                                <!-- <td data-th="Playered" width="10%" class="text-center">3</td> -->
                                <td data-th="Won" width="10%" class="text-center">{{each.wins}}</td>
                                <td data-th="Draw" width="10%" class="text-center">{{each.draws}}</td>
                                <td data-th="Lost" width="10%" class="text-center">{{each.lose}}</td>
                                <td data-th="For" width="10%" class="text-center">{{each.goal_for}}</td>
                                <td data-th="Against" width="10%" class="text-center">{{each.goal_against}}</td>
                                <td data-th="Goal dif." width="10%" class="text-center">{{each.goal_diff}}</td>
                                <td data-th="Points" width="10%" class="text-center">{{each.points}}</td>
                              </tr>
                              {% endfor %}

                            </tbody>
                          </table>

                        </div>
                      </div>

                    </div>
                  </div>
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/stats/teams.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Teams
{% endblock title %}

{% block content %}
<!-- START PAGE TITILE SECTION -->
<div class="player-profile-section page-title-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="section-title profile-title">
                        <h1>DAFL Teams</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END OF /. PAGE TITLE SECTION -->

    <div class="blog-container-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="blog-container">
                        <!-- START BLOG ITEMS -->
                        {% for each in competitions %}
                          <div class="title-section">
                              <h2><b>{{each.name}}</b></h2>
                          </div>
                              <div class="row">
                                {% for x in each.team_set.all %}
                                  <div class="col-md-2" style="margin-bottom:15px;">
                                    {% if x.logo %}
                                    <a href="{% url "stats:team-page" x.pk x.name|slugify %}"><img src="{{x.logo.url}}" class="img-responsive" style="width:300px;" /></a>
                                    <p style="text-align:center;"><a href="{% url "stats:team-page" x.pk x.name|slugify %}"><b>{{x.name}}</b></a></p>
                                    {% else %}
                                    <p style="text-align:center;"><a href="{% url "stats:team-page" x.pk x.name|slugify %}"><b>{{x.name}}</b></a></p>
                                    {% endif %}
                                  </div>
                                {% endfor %}
                              </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div><!-- END OF /. BLOG CONTAINER SECTION -->

{% endblock content %}